WITH MON_USAGE AS(
	SELECT
	SDP_WID,
	LAST_DAY(TO_DATE(DATE_WID)) AS MONTH_END,
	SUM(INTERVAL_VALUE) AS MONTHLY_USAGE
	FROM "YOURSCHEMA"."EIP_RA.EIP_RA_USR.INTERVAL_F"
	WHERE INTERVAL_END_TIME 
	BETWEEN TO_TIMESTAMP(ADD_DAYS(ADD_MONTHS(LAST_DAY(CURRENT_TIMESTAMP),-2),1)) 
	AND TO_TIMESTAMP(ADD_MONTHS(LAST_DAY(CURRENT_TIMESTAMP),-1))
	GROUP BY 
	SDP_WID,
	LAST_DAY(TO_DATE(DATE_WID))
)

-- REQ-3.0
WITH DNP_3_DAYS AS(
	SELECT 
	ESI_ID
	MAX(ACTUAL_END_TS) AS LAST_DNP_TS
	FROM "YOURSCHEMA"."STG.T_STG_EAI_SVC_ORDERS_HIST"
	WHERE ACTUAL_END_TS 
	BETWEEN TO_TIMESTAMP(ADD_DAYS(ADD_MONTHS(TO_DATE(CURRENT_TIMESTAMP),-2),1)) 
	AND TO_TIMESTAMP(ADD_MONTHS(TO_DATE(CURRENT_TIMESTAMP),-1))
	AND BPI_STATE NOT LIKE '%CANCEL%'
	AND JOB_CD LIKE '%DNP%'
	GROUP BY ESI_ID
)

WITH CREW_ONSITE AS(	
	SELECT DISTINCT
		ESI_ID
		ONSITE_DT + ' ' + ONSITE_TIME AS ONSITE_TS
		RANK()OVER(PARTITION BY ESI_ID 
		ORDER BY TO_TIMESTAMP(ONSITE_DT || ' ' || ONSITE_TIME), 'YYYY-MM-DD HH24:MI:ss') DESC)) as rk
	FROM "YOURSCHEMA"."STG.T_MOBILE_DATA_CREW_ONSITE_HIST"
	WHERE JOB_CODE LIKE '%TBL%'
)

WITH PREMISE_INFO AS(
	SELECT
		ESI_ID,
		ELEC_ACCT_ID,
		ACCT_NUM_11
		STREET_NUMBER
		STREET_NAME,
		STREET_APARTMENT,
		CITY,
		ZIPCODE,
		SERVICE_CENTER,
		ROUTE
	FROM "YOURSCHEMA"."STG.PREMISE_CHAR"
)


WITH STATUS AS(
	SELECT
		MS_UNGR
	FROM "YOURSCHEMA"."STG.T_STG_EAI_SVC_ORDERS_HIST"
)

SELECT *
FROM DNP_3_DAYS
LEFT JOIN MON_USAGE
ON DNP_3_DAYS.ESI_ID = MON_USAGE.SDP_WID
LEFT JOIN "YOURSCHEMA"."EIP_RA.EIP_RA_USR.SDP_D" b
ON MON_USAGE.SDP_WID = b.WID
WHERE MONTHLY_USAGE > 200
LEFT JOIN CREW_ONSITE
ON b.WID = CREW_ONSITE.ESI_ID
WHERE rk = 1
LEFT JOIN PREMISE_INFO
ON CREW_ONSITE.ESI_ID = PREMISE_INFO.ESI_ID
LEFT JOIN STATUS
ON PREMISE_INFO.ESI_ID = STATUS.ESI_ID
)
	
